name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - name: Checkout finalize_helper
        uses: actions/checkout@v4

      - name: Checkout GodMode9
        uses: actions/checkout@v4
        with:
          repository: d0k3/GodMode9
          path: GodMode9
          ref: v2.1.1

      - name: Install packages
        run: |
          apt-get update
          apt-get -y install dirmngr python3 python3-pip p7zip-full libarchive13
          python3 -m pip install setuptools cryptography git+https://github.com/TuxSH/firmtool.git

      - name: Install 3dstool
        run: |
          wget https://github.com/dnasdw/3dstool/releases/download/v1.2.6/3dstool_linux_x86_64.tar.gz
          tar xvzf 3dstool_linux_x86_64.tar.gz
          sudo cp 3dstool ext_key.txt ignore_3dstool.txt /usr/local/bin
          sudo chmod a+x /usr/local/bin/3dstool

      - name: Build Project
        run: |
          make

      - uses: actions/upload-artifact@v4
        with:
          name: finalize_helper
          path: builds
          if-no-files-found: error
